export const BASE = {
  sitePassword: "HelloDave",
  adminPassword: "asdf",
  defaultInterval: 1 * 60 * 1000, 
  defaultLockout: 10 * 1000, 
};

export const CLUES = [
  {
    id: 1,
    type: "text",
    question: "In 1880 the Victorian Government issued a reward for the capture of Australia's most wanted man.\n\nWho was he?",
    check: (v) => ["ned kelly", "kelly", "edward kelly"].includes(v.toLowerCase().trim()),
    placeholder: "name…",
    hint: "He wore a homemade iron helmet. He was not subtle.",
    flavor: "£8,000. Not a bad price for one man.",
    adminLabel: "Ned Kelly reward",
    adminAnswer: "Ned Kelly",
  },
  {
    id: 2,
    type: "body_map",
    question: "A person runs 10km every day for a full year.\n\nWhich muscle group does research identify as the primary driver of forward propulsion — not stabilisation, not cushioning, but propulsion?",
    options: [
      { id: "foot", label: "Foot", x: 50, y: 92 },
      { id: "calf", label: "Calf", x: 50, y: 80 },
      { id: "thigh", label: "Thigh", x: 50, y: 65 },
      { id: "glute", label: "Glute", x: 50, y: 52 },
    ],
    answer: "calf",
    hint: "Below the knee. Behind the shin. You use it constantly.",
    flavor: "Below the knee. Behind the shin. You use it constantly.",
    adminLabel: "Muscle propulsion",
    adminAnswer: "Calf / Soleus",
  },
  {
    id: 3,
    type: "choice",
    quote: "Friendship is the inexpressible comfort of feeling safe with a person — having neither to weigh thoughts nor measure words.",
    question: "Who wrote this?",
    options: [
      "George Eliot", "Virginia Woolf", "Oscar Wilde", "Maya Angelou", 
      "Jane Austen", "Emily Bronte", "Charles Dickens", "Leo Tolstoy", 
      "Thomas Hardy", "George Sand"
    ],
    answer: "George Eliot",
    hint: "Victorian novelist. Wrote under a pen name.",
    flavor: "She knew something about what it means to feel genuinely at ease.",
    adminLabel: "Friendship quote",
    adminAnswer: "George Eliot",
  },
  {
    id: 4,
    type: "counter",
    question: "How many VFL/AFL premierships has the Collingwood Football Club won, as of their most recent victory in 2023?",
    startValue: 12,
    answer: 16,
    hint: "Google it. No shame in that.",
    flavor: "16 flags. Go Pies.",
    adminLabel: "Collingwood flags",
    adminAnswer: "16",
  },
  {
    id: 5,
    type: "buildings_tiles",
    question: "Name each of these five buildings or structures and where they are located.",
    images: [
      { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Acropolis_in_Athens%2C_Greece.jpg/640px-Acropolis_in_Athens%2C_Greece.jpg", name: "Acropolis of Athens", city: "Athens" },
      { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Chichen_Itza_El_Castillo%2C_Mexico.jpg/640px-Chichen_Itza_El_Castillo%2C_Mexico.jpg", name: "El Castillo", city: "Chichén Itzá" },
      { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Taj_Mahal_in_March_2004.jpg/640px-Taj_Mahal_in_March_2004.jpg", name: "Taj Mahal", city: "Agra" },
      { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Petra_Jordan_BW_25.JPG/640px-Petra_Jordan_BW_25.JPG", name: "The Treasury", city: "Petra" },
      { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Angkor_Wat_temple.jpg/640px-Angkor_Wat_temple.jpg", name: "Angkor Wat", city: "Siem Reap" }
    ],
    tiles: [
      "Acropolis of Athens", "El Castillo", "Taj Mahal", "The Treasury", "Angkor Wat",
      "Athens", "Chichén Itzá", "Agra", "Petra", "Siem Reap"
    ],
    hint: "Each is an iconic work of ancient ingenuity found across three continents.",
    flavor: "Timeless landmarks that keep drawing curious travelers.",
    adminLabel: "5 Buildings tiles",
    adminAnswer: "Acropolis, El Castillo, Taj Mahal, Treasury, Angkor Wat",
  },
  {
    id: 6,
    type: "choice",
    question: "What do all five of those places have in common?",
    options: [
      "All were built before 1900",
      "All were once government-owned",
      "All were built for one purpose and now serve a completely different one",
      "All are located in capital cities",
      "All were designed by female architects",
      "All were nearly demolished before being repurposed",
      "All feature in major motion pictures",
      "All are free to enter",
      "All have underground facilities",
      "All are made primarily of brick"
    ],
    answer: "All were built for one purpose and now serve a completely different one",
    hint: "Ignore the architecture answers. Think bigger.",
    flavor: "Everything can become something else.",
    adminLabel: "Buildings commonality",
    adminAnswer: "Repurposed",
  },
  {
    id: 7,
    type: "number_unit",
    question: "Vipassana meditation as taught by S.N. Goenka in the tradition of Sayagyi U Ba Khin requires participants to remain in complete silence for the entire duration of its foundational course.\n\nHow long does it run for?",
    startValue: 7,
    units: ["days", "weeks", "months", "hours"],
    answer: { value: 10, unit: "days" },
    hint: "A round number. Not a small one.",
    flavor: "Ten days of silence. It changes you.",
    adminLabel: "Vipassana duration",
    adminAnswer: "10 days",
  },
  {
    id: 8,
    type: "selection_slots",
    question: "A chef is preparing fresh pasta from scratch.\n\nBefore the pasta enters the pot, what three things must already be in it?",
    slots: 3,
    options: ["Boiling water", "Salt", "Oil", "Butter", "Garlic", "Onion", "Herbs", "Wine", "Lemon", "Black Pepper"],
    answers: ["Boiling water", "Salt", "Oil"],
    hint: "Not pasta ingredients. What's already in the pot before anything goes in.",
    flavor: "Water, salt, oil. The fundamentals.",
    adminLabel: "Pasta ingredients",
    adminAnswer: "Water, Salt, Oil",
  },
  {
    id: 9,
    type: "numeral",
    digits: 3,
    question: "A rectangular garden has a perimeter of 78 metres.\n\nThe length is 11 metres more than the width.\n\nWhat is the area in square metres?",
    answer: "350",
    hint: "Perimeter = 2(l + w). Length = width + 11. Solve for width first.",
    flavor: "350. Hold onto that number.",
    adminLabel: "Garden algebra (350)",
    adminAnswer: "350",
  },
  {
    id: 10,
    type: "letter_slots",
    question: "Roman soldiers were sometimes paid partly in salt — it was that valuable.\n\nWhat common English word derives directly from the Latin word for salt, sal?",
    answer: "SALARY",
    hint: "It's a word you use every time you talk about money.",
    flavor: "Salary. A word shaped by salt.",
    adminLabel: "Salt salary origin",
    adminAnswer: "Salary",
  },
  {
    id: 11,
    type: "choice",
    question: "Archaeological evidence suggests linen fabric was first developed by which ancient civilisation, making it one of the oldest textiles in the world?",
    options: ["Ancient Egypt", "Ancient Greece", "Mesopotamia", "The Indus Valley", "The Maya", "The Aztecs", "Ancient China", "Persia", "Rome", "Phoenicia"],
    answer: "Ancient Egypt",
    hint: "They also used it to wrap their dead.",
    flavor: "Linen. The fabric of the Nile.",
    adminLabel: "Linen origin",
    adminAnswer: "Ancient Egypt",
  },
  {
    id: 12,
    type: "dual_slider",
    question: "Set the temperature at which water freezes. Set the temperature at which water boils.",
    range: [-50, 200],
    answers: [0, 100],
    tolerance: 2,
    hint: "You learned this in primary school.",
    flavor: "Zero and one hundred. The bounds of water.",
    adminLabel: "Freeze/Boil temps",
    adminAnswer: "0°C and 100°C",
  },
  {
    id: 13,
    type: "choice",
    question: "After exercise, ancient Greek athletes would scrape oil, sweat and dirt from their skin using a curved metal tool.\n\nWhat was this tool called?",
    options: ["Strigil", "Cestus", "Halteres", "Chiton", "Kantharos", "Silenus", "Trireme", "Amphora", "Caduceus", "Thyrsus"],
    answer: "Strigil",
    hint: "It's not a word you use today. It's from Ancient Greek.",
    flavor: "A strigil. A lost artifact of athleticism.",
    adminLabel: "Ancient Greek scraper",
    adminAnswer: "Strigil",
  },
  {
    id: 14,
    type: "slider",
    question: "What percentage of the average adult human body is composed of water?",
    range: [0, 100],
    answer: 60,
    tolerance: 3,
    unit: "%",
    hint: "More than half. Less than three quarters.",
    flavor: "60% of you is water.",
    adminLabel: "Human body water %",
    adminAnswer: "60%",
  },
  {
    id: 15,
    type: "choice",
    question: "Long before graduation ceremonies or royal courts, a single draped garment without stitching defined the formal dress of an entire civilisation for centuries.\n\nWhich civilisation?",
    options: ["Ancient Greece", "Ancient Rome", "The Ottoman Empire", "The Han Dynasty", "Ancient Egypt", "The Vikings", "The Mongols", "The Incas", "Ancient Persia", "The Aztecs"],
    answer: "Ancient Rome",
    hint: "One piece of fabric. No stitching. An entire empire dressed in it.",
    flavor: "The toga. One piece of fabric, one empire.",
    adminLabel: "Roman garment",
    adminAnswer: "Ancient Rome",
  },
  {
    id: 16,
    type: "choice",
    question: "Roman engineers invented a system of raised floors and hollow walls through which hot air circulated from a furnace below.\n\nUsed in homes, public spaces, and communal gathering buildings.\n\nWhat was it called?",
    options: [
      "Hypocaust", "Aqueduct", "Forum", "Basilica", "Circus", 
      "Thermae", "Atrium", "Vestibule", "Peristyle", "Calidarium"
    ],
    answer: "Hypocaust",
    lockoutMs: 15 * 60 * 1000,
    hint: "A single Greek-derived word. Googleable.",
    flavor: "The hypocaust. Ancient warmth.",
    adminLabel: "Roman heating (15min lockout)",
    adminAnswer: "Hypocaust",
  },
  {
    id: 17,
    type: "selection_slots",
    question: "Cotton cultivation has been traced back approximately how many years — and to which two ancient civilisations that developed it independently, with no contact between each other?",
    slots: 3,
    options: ["7,000 years", "Indus Valley", "Mesoamerica", "3,000 years", "5,000 years", "Ancient Egypt", "Summarians", "China", "Incas", "Mayas"],
    answers: ["7,000 years", "Indus Valley", "Mesoamerica"],
    hint: "Two civilisations. Completely separate. Same discovery.",
    flavor: "7,000 years of a single thread.",
    adminLabel: "Cotton origin",
    adminAnswer: "7,000 yrs / Indus & Mesoamerica",
  },
  {
    id: 18,
    type: "choice",
    question: "Finland has the highest number of saunas per capita of any country on earth.\n\nApproximately how many saunas exist in Finland for a population of around 5.5 million people?",
    options: [
      "3.2 million (roughly one per person)", 
      "1.5 million", 
      "500,000", 
      "5.5 million", 
      "1 million", 
      "2 million", 
      "4.1 million", 
      "800,000", 
      "2.2 million", 
      "6 million"
    ],
    answer: "3.2 million (roughly one per person)",
    hint: "More saunas than cars. Think about that.",
    flavor: "3.2 million saunas. Steam is life in Finland.",
    adminLabel: "Finland saunas",
    adminAnswer: "3.2 million",
  },
  {
    id: 19,
    type: "choice",
    question: "Which of these cities is widely considered the oldest continuously inhabited city in the world?",
    options: [
      "Rome", "Damascus", "Jerusalem", "Jericho", "Athens", "Sana'a", "Lisbon", "Beijing", "Kyoto", "Istanbul"
    ],
    answer: "Jericho",
    hint: "It sits beside the Jordan River and has ruins older than 10,000 years.",
    flavor: "Jericho. Whispered to be one of the very first settlements.",
    adminLabel: "Oldest city",
    adminAnswer: "Jericho",
  },
  {
    id: 20,
    type: "text",
    question: "What Sanskrit word names the vital life force or breath that yoga aims to connect with?",
    check: (v) => v.toLowerCase().trim() === "prana",
    placeholder: "prana…",
    hint: "It rhymes with 'sana' and flows through every breath.",
    flavor: "Prana. The breath that carries intention.",
    adminLabel: "Prana life force",
    adminAnswer: "Prana",
  },
  {
    id: 21,
    type: "slider",
    question: "Roughly what percentage of Earth's surface is covered by oceans?",
    range: [0, 100],
    answer: 71,
    tolerance: 2,
    unit: "%",
    hint: "More than two-thirds, less than three-quarters.",
    flavor: "71%. Water wraps the planet.",
    adminLabel: "Ocean coverage",
    adminAnswer: "71%",
  },
  {
    id: 22,
    type: "choice",
    question: "Which composer wrote the piano piece 'Clair de Lune'?",
    options: [
      "Claude Debussy", "Frédéric Chopin", "Ludwig van Beethoven", "Béla Bartók", "Erik Satie", "Maurice Ravel",
      "Camille Saint-Saëns", "Igor Stravinsky", "Philip Glass", "Aaron Copland"
    ],
    answer: "Claude Debussy",
    hint: "The composer who painted moonlight with impressionist brushstrokes.",
    flavor: "Debussy. Moonlight shimmering across the keys.",
    adminLabel: "Clair de Lune",
    adminAnswer: "Claude Debussy",
  },
  {
    id: 23,
    type: "selection_slots",
    question: "A classic Negroni is made from three ingredients before it hits the rocks. Which ones?",
    slots: 3,
    options: ["Gin", "Campari", "Vermouth", "Orange peel", "Lemon juice", "Soda water", "Tonic", "Angostura bitters", "Sugar", "Prosecco"],
    answers: ["Gin", "Campari", "Vermouth"],
    hint: "Bitter, sweet, botanical. Stirred, then garnished.",
    flavor: "Gin, Campari and vermouth. A bitter geometry in a glass.",
    adminLabel: "Negroni ingredients",
    adminAnswer: "Gin, Campari, Vermouth",
  },
  {
    id: 24,
    type: "numeral",
    digits: 2,
    question: "A right triangle has legs measuring 7 and 24. What is the length of the hypotenuse, rounded to the nearest whole number?",
    answer: "25",
    hint: "Pythagoras knew this triple well.",
    flavor: "7-24-25. The hypotenuse stands tall.",
    adminLabel: "Hypotenuse 7-24-25",
    adminAnswer: "25",
  },
  {
    id: 25,
    type: "text",
    question: "The ancient Greek aphorism inscribed in the Temple of Apollo at Delphi urges you to do what?",
    check: (v) => {
      const normalized = v.toLowerCase().replace(/[^a-z ]/g, '').trim();
      return ["know thyself", "know yourself", "gnothi seauton"].includes(normalized);
    },
    placeholder: "know thyself…",
    hint: "Two simple words, whispered over centuries.",
    flavor: "Know thyself. The Oracle still hums this advice.",
    adminLabel: "Delphi inscription",
    adminAnswer: "Know thyself",
  },
];

export const REVEAL_PAIRS = [
  ["Ned Kelly.", "£8,000 for one man."],
  ["The calf.", "The driver of propulsion."],
  ["George Eliot.", "Comfort of feeling safe."],
  ["16 flags.", "Go Pies."],
  [" Landmarks & Cities.", "They are famous landscapes with new lives."],
  ["Repurposed buildings.", "Everything can become something else."],
  ["10 days of silence.", "It changes you."],
  ["Boiling water, salt and oil.", "The fundamentals, always."],
  ["350 square metres.", "Hold onto that number."],
  ["Salary.", "A word shaped by salt."],
  ["Linen fabric.", "The fabric of the Nile."],
  ["Freezing & Boiling.", "0 and 100 degrees."],
  ["The strigil.", "Scraping sweat and oil."],
  ["60% water.", "You are mostly liquid."],
  ["Ancient Rome.", "The Drape without stitch."],
  ["The hypocaust.", "Heat from below."],
  ["7,000 years of cotton.", "A single thread."],
  ["3.2 million saunas.", "Steam is life."],
  ["Jericho.", "One of the oldest doors in the world."],
  ["Prana.", "Breath that hums through the body."],
  ["71% ocean.", "Water wraps the blue planet."],
  ["Claude Debussy.", "Moonlight painted in sound."],
  ["Gin, Campari & Vermouth.", "The Negroni's bitter geometry."],
  ["25.", "Pythagoras gives it away."],
  ["Know thyself.", "Delphi still whispers."],
];
