export const BASE = {
  sitePassword: "HelloDave",
  adminPassword: "asdf",
  defaultInterval: 1 * 60 * 1000, 
  defaultLockout: 10 * 1000, 
};

export const CLUES = [
  {
    id: 1,
    type: "text",
    question: "In 1880 the Victorian Government issued a reward for the capture of Australia's most wanted man.\n\nWho was he?",
    check: (v) => ["ned kelly", "kelly", "edward kelly"].includes(v.toLowerCase().trim()),
    placeholder: "name…",
    hint: "He wore a homemade iron helmet. He was not subtle.",
    flavor: "£8,000. Not a bad price for one man.",
    adminLabel: "Ned Kelly reward",
    adminAnswer: "Ned Kelly",
  },
  {
    id: 2,
    type: "body_map",
    question: "A person runs 10km every day for a full year.\n\nWhich muscle group does research identify as the primary driver of forward propulsion — not stabilisation, not cushioning, but propulsion?",
    options: [
      { id: "foot", label: "Foot", x: 50, y: 92 },
      { id: "calf", label: "Calf", x: 50, y: 80 },
      { id: "thigh", label: "Thigh", x: 50, y: 65 },
      { id: "glute", label: "Glute", x: 50, y: 52 },
    ],
    answer: "calf",
    hint: "Below the knee. Behind the shin. You use it constantly.",
    flavor: "Below the knee. Behind the shin. You use it constantly.",
    adminLabel: "Muscle propulsion",
    adminAnswer: "Calf / Soleus",
  },
  {
    id: 3,
    type: "choice",
    quote: "Friendship is the inexpressible comfort of feeling safe with a person — having neither to weigh thoughts nor measure words.",
    question: "Who wrote this?",
    options: [
      "George Eliot", "Virginia Woolf", "Oscar Wilde", "Maya Angelou", 
      "Jane Austen", "Emily Bronte", "Charles Dickens", "Leo Tolstoy", 
      "Thomas Hardy", "George Sand"
    ],
    answer: "George Eliot",
    hint: "Victorian novelist. Wrote under a pen name.",
    flavor: "She knew something about what it means to feel genuinely at ease.",
    adminLabel: "Friendship quote",
    adminAnswer: "George Eliot",
  },
  {
    id: 4,
    type: "counter",
    question: "How many VFL/AFL premierships has the Collingwood Football Club won, as of their most recent victory in 2023?",
    startValue: 12,
    answer: 16,
    hint: "Google it. No shame in that.",
    flavor: "16 flags. Go Pies.",
    adminLabel: "Collingwood flags",
    adminAnswer: "16",
  },
  {
    id: 5,
    type: "buildings_tiles",
    question: "Name each of these five buildings or structures and where they are located.",
    images: [
      { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Tate_Modern_from_the_south.jpg/640px-Tate_Modern_from_the_south.jpg", name: "Tate Modern", city: "London" },
      { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Mus%C3%A9e_d%27Orsay_2014%28cropped%29.jpg/640px-Mus%C3%A9e_d%27Orsay_2014%28cropped%29.jpg", name: "Musée d'Orsay", city: "Paris" },
      { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/High_Line_-_Section_2_opening.jpg/640px-High_Line_-_Section_2_opening.jpg", name: "The High Line", city: "New York" },
      { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Battersea_Power_Station_from_the_north.jpg/640px-Battersea_Power_Station_from_the_north.jpg", name: "Battersea Power Station", city: "London" },
      { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Wien_-_Gasometer_%28Au%C3%9Fenansicht%29.jpg/640px-Wien_-_Gasometer_%28Au%C3%9Fenansicht%29.jpg", name: "Gasometer", city: "Vienna" }
    ],
    tiles: [
      "Tate Modern", "Musée d'Orsay", "The High Line", "Battersea Power Station", "Gasometer",
      "London", "Paris", "New York", "London", "Vienna"
    ],
    hint: "They're all famous. One is in New York, three in Europe, one in Vienna.",
    flavor: "They're all famous landmarks with new lives.",
    adminLabel: "5 Buildings tiles",
    adminAnswer: "Tate, Orsay, High Line, Battersea, Gasometer",
  },
  {
    id: 6,
    type: "choice",
    question: "What do all five of those places have in common?",
    options: [
      "All were built before 1900",
      "All were once government-owned",
      "All were built for one purpose and now serve a completely different one",
      "All are located in capital cities",
      "All were designed by female architects",
      "All were nearly demolished before being repurposed",
      "All feature in major motion pictures",
      "All are free to enter",
      "All have underground facilities",
      "All are made primarily of brick"
    ],
    answer: "All were built for one purpose and now serve a completely different one",
    hint: "Ignore the architecture answers. Think bigger.",
    flavor: "Everything can become something else.",
    adminLabel: "Buildings commonality",
    adminAnswer: "Repurposed",
  },
  {
    id: 7,
    type: "number_unit",
    question: "Vipassana meditation as taught by S.N. Goenka in the tradition of Sayagyi U Ba Khin requires participants to remain in complete silence for the entire duration of its foundational course.\n\nHow long does it run for?",
    startValue: 7,
    units: ["days", "weeks", "months", "hours"],
    answer: { value: 10, unit: "days" },
    hint: "A round number. Not a small one.",
    flavor: "Ten days of silence. It changes you.",
    adminLabel: "Vipassana duration",
    adminAnswer: "10 days",
  },
  {
    id: 8,
    type: "selection_slots",
    question: "A chef is preparing fresh pasta from scratch.\n\nBefore the pasta enters the pot, what three things must already be in it?",
    slots: 3,
    options: ["Boiling water", "Salt", "Oil", "Butter", "Garlic", "Onion", "Herbs", "Wine", "Lemon", "Black Pepper"],
    answers: ["Boiling water", "Salt", "Oil"],
    hint: "Not pasta ingredients. What's already in the pot before anything goes in.",
    flavor: "Water, salt, oil. The fundamentals.",
    adminLabel: "Pasta ingredients",
    adminAnswer: "Water, Salt, Oil",
  },
  {
    id: 9,
    type: "numeral",
    digits: 3,
    question: "A rectangular garden has a perimeter of 78 metres.\n\nThe length is 11 metres more than the width.\n\nWhat is the area in square metres?",
    answer: "350",
    hint: "Perimeter = 2(l + w). Length = width + 11. Solve for width first.",
    flavor: "350. Hold onto that number.",
    adminLabel: "Garden algebra (350)",
    adminAnswer: "350",
  },
  {
    id: 10,
    type: "letter_slots",
    question: "Roman soldiers were sometimes paid partly in salt — it was that valuable.\n\nWhat common English word derives directly from the Latin word for salt, sal?",
    answer: "SALARY",
    hint: "It's a word you use every time you talk about money.",
    flavor: "Salary. A word shaped by salt.",
    adminLabel: "Salt salary origin",
    adminAnswer: "Salary",
  },
  {
    id: 11,
    type: "choice",
    question: "Archaeological evidence suggests linen fabric was first developed by which ancient civilisation, making it one of the oldest textiles in the world?",
    options: ["Ancient Egypt", "Ancient Greece", "Mesopotamia", "The Indus Valley", "The Maya", "The Aztecs", "Ancient China", "Persia", "Rome", "Phoenicia"],
    answer: "Ancient Egypt",
    hint: "They also used it to wrap their dead.",
    flavor: "Linen. The fabric of the Nile.",
    adminLabel: "Linen origin",
    adminAnswer: "Ancient Egypt",
  },
  {
    id: 12,
    type: "dual_slider",
    question: "Set the temperature at which water freezes. Set the temperature at which water boils.",
    range: [-50, 200],
    answers: [0, 100],
    tolerance: 2,
    hint: "You learned this in primary school.",
    flavor: "Zero and one hundred. The bounds of water.",
    adminLabel: "Freeze/Boil temps",
    adminAnswer: "0°C and 100°C",
  },
  {
    id: 13,
    type: "choice",
    question: "After exercise, ancient Greek athletes would scrape oil, sweat and dirt from their skin using a curved metal tool.\n\nWhat was this tool called?",
    options: ["Strigil", "Cestus", "Halteres", "Chiton", "Kantharos", "Silenus", "Trireme", "Amphora", "Caduceus", "Thyrsus"],
    answer: "Strigil",
    hint: "It's not a word you use today. It's from Ancient Greek.",
    flavor: "A strigil. A lost artifact of athleticism.",
    adminLabel: "Ancient Greek scraper",
    adminAnswer: "Strigil",
  },
  {
    id: 14,
    type: "slider",
    question: "What percentage of the average adult human body is composed of water?",
    range: [0, 100],
    answer: 60,
    tolerance: 3,
    unit: "%",
    hint: "More than half. Less than three quarters.",
    flavor: "60% of you is water.",
    adminLabel: "Human body water %",
    adminAnswer: "60%",
  },
  {
    id: 15,
    type: "choice",
    question: "Long before graduation ceremonies or royal courts, a single draped garment without stitching defined the formal dress of an entire civilisation for centuries.\n\nWhich civilisation?",
    options: ["Ancient Greece", "Ancient Rome", "The Ottoman Empire", "The Han Dynasty", "Ancient Egypt", "The Vikings", "The Mongols", "The Incas", "Ancient Persia", "The Aztecs"],
    answer: "Ancient Rome",
    hint: "One piece of fabric. No stitching. An entire empire dressed in it.",
    flavor: "The toga. One piece of fabric, one empire.",
    adminLabel: "Roman garment",
    adminAnswer: "Ancient Rome",
  },
  {
    id: 16,
    type: "choice",
    question: "Roman engineers invented a system of raised floors and hollow walls through which hot air circulated from a furnace below.\n\nUsed in homes, public spaces, and communal gathering buildings.\n\nWhat was it called?",
    options: [
      "Hypocaust", "Aqueduct", "Forum", "Basilica", "Circus", 
      "Thermae", "Atrium", "Vestibule", "Peristyle", "Calidarium"
    ],
    answer: "Hypocaust",
    lockoutMs: 15 * 60 * 1000,
    hint: "A single Greek-derived word. Googleable.",
    flavor: "The hypocaust. Ancient warmth.",
    adminLabel: "Roman heating (15min lockout)",
    adminAnswer: "Hypocaust",
  },
  {
    id: 17,
    type: "selection_slots",
    question: "Cotton cultivation has been traced back approximately how many years — and to which two ancient civilisations that developed it independently, with no contact between each other?",
    slots: 3,
    options: ["7,000 years", "Indus Valley", "Mesoamerica", "3,000 years", "5,000 years", "Ancient Egypt", "Summarians", "China", "Incas", "Mayas"],
    answers: ["7,000 years", "Indus Valley", "Mesoamerica"],
    hint: "Two civilisations. Completely separate. Same discovery.",
    flavor: "7,000 years of a single thread.",
    adminLabel: "Cotton origin",
    adminAnswer: "7,000 yrs / Indus & Mesoamerica",
  },
  {
    id: 18,
    type: "choice",
    question: "Finland has the highest number of saunas per capita of any country on earth.\n\nApproximately how many saunas exist in Finland for a population of around 5.5 million people?",
    options: [
      "3.2 million (roughly one per person)", 
      "1.5 million", 
      "500,000", 
      "5.5 million", 
      "1 million", 
      "2 million", 
      "4.1 million", 
      "800,000", 
      "2.2 million", 
      "6 million"
    ],
    answer: "3.2 million (roughly one per person)",
    hint: "More saunas than cars. Think about that.",
    flavor: "3.2 million saunas. Steam is life in Finland.",
    adminLabel: "Finland saunas",
    adminAnswer: "3.2 million",
  },
];

export const REVEAL_PAIRS = [
  ["Ned Kelly.", "£8,000 for one man."],
  ["The calf.", "The driver of propulsion."],
  ["George Eliot.", "Comfort of feeling safe."],
  ["16 flags.", "Go Pies."],
  [" Landmarks & Cities.", "They are famous landscapes with new lives."],
  ["Repurposed buildings.", "Everything can become something else."],
  ["10 days of silence.", "It changes you."],
  ["Boiling water, salt and oil.", "The fundamentals, always."],
  ["350 square metres.", "Hold onto that number."],
  ["Salary.", "A word shaped by salt."],
  ["Linen fabric.", "The fabric of the Nile."],
  ["Freezing & Boiling.", "0 and 100 degrees."],
  ["The strigil.", "Scraping sweat and oil."],
  ["60% water.", "You are mostly liquid."],
  ["Ancient Rome.", "The Drape without stitch."],
  ["The hypocaust.", "Heat from below."],
  ["7,000 years of cotton.", "A single thread."],
  ["3.2 million saunas.", "Steam is life."],
];
